### ISSUE TITLE
Issue with TrainingDataAnnotator.java

### ISSUE THREAD

**Issue by suburbianmantia** [mkrnr/refext#1]
Hi there, 

I am a newbie in Java language but I wanted to learn more about machine learning for references extraction. 

I wanted to create a CRF model file with TrainingDataAnnotator.java, but when I run it, the following error occurs: `

```
Exception in thread "main" java.lang.RuntimeException: java.io.StreamCorruptedException: invalid stream header: 45787065
	at cc.mallet.util.FileUtils.readUnzippedObject(FileUtils.java:84)
	at cc.mallet.util.FileUtils.readObject(FileUtils.java:64)
	at de.exciteproject.refext.extract.ReferenceLineAnnotator.<init>(ReferenceLineAnnotator.java:36)
	at de.exciteproject.refext.ReferenceExtractor.<init>(ReferenceExtractor.java:28)
	at de.exciteproject.refext.train.TrainingDataAnnotator.<init>(TrainingDataAnnotator.java:60)
	at de.exciteproject.refext.train.TrainingDataAnnotator.main(TrainingDataAnnotator.java:31)
Caused by: java.io.StreamCorruptedException: invalid stream header: 45787065
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:963)
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:397)
	at cc.mallet.util.FileUtils.readUnzippedObject(FileUtils.java:78)
	... 5 more

```
And here is the code: 
```
package de.exciteproject.refext.train;

import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import org.apache.commons.io.FilenameUtils;

import de.exciteproject.refext.ReferenceExtractor;
import de.exciteproject.refext.extract.ReferenceLineAnnotation;
import de.exciteproject.refext.util.FileUtils;
import pl.edu.icm.cermine.exception.AnalysisException;

/**
 * Simplified annotator for generating training data. Does not handle
 * footers/headers that appear inside a reference string.
 */
public class TrainingDataAnnotator {

    public static void main(String[] args) throws AnalysisException, IOException {
        File crfModelFile = new File("C:\\Users\\myname\\OneDrive\\Bureau\\javas\\chopra2016.csv");
        File inputDir = new File("C:\\Users\\myname\\OneDrive\\Bureau\\javas");
        File outputDir = new File("C:\\Users\\myname\\OneDrive\\Bureau\\javas");
        if (!outputDir.exists()) {
            outputDir.mkdirs();
        }
        TrainingDataAnnotator trainingDataAnnotator = new TrainingDataAnnotator(crfModelFile);
        List<File> inputFiles = FileUtils.asList(inputDir);

        for (File inputFile : inputFiles) {
            String subDirectories = inputFile.getParentFile().getAbsolutePath().replace("\\", "/")
                    .replaceFirst(inputDir.getAbsolutePath().replace("\\", "/"), "");
            //File currentOutputDirectory = new File(outputDir.getAbsolutePath() + File.separator + subDirectories);
            File currentOutputDirectory = new File(outputDir.getAbsolutePath());

            String outputFileName = FilenameUtils.removeExtension(inputFile.getName()) + ".csv";
            File outputFile = new File(currentOutputDirectory + File.separator + outputFileName);

            // skip computation if outputFile already exists
            if (outputFile.exists()) {
                continue;
            }
            if (!currentOutputDirectory.exists()) {
                currentOutputDirectory.mkdirs();
            }

            List<String> annotatedText = trainingDataAnnotator.annotateText(inputFile);
            Files.write(Paths.get(outputFile.getAbsolutePath()), annotatedText, Charset.defaultCharset());
            //Files.write(Paths.get(outputFile.getAbsolutePath().replace("\\", "/")), annotatedText, Charset.defaultCharset());
        }
    }

    private ReferenceExtractor referenceExtractor;

    public TrainingDataAnnotator(File crfModelFile) throws AnalysisException {
        this.referenceExtractor = new ReferenceExtractor(crfModelFile);
    }
    

    public List<String> annotateText(File layoutFile) throws IOException, AnalysisException {
        List<ReferenceLineAnnotation> annotatedLines = this.referenceExtractor.annotateLinesFromLayoutFile(layoutFile,
                Charset.defaultCharset());

        List<String> xmlAnnotatedLines = new ArrayList<String>();
        for (int i = 0; i < annotatedLines.size(); i++) {
            boolean addStartTag = false;
            boolean addEndTag = false;
            // System.out.println(annotatedLines.get(i));
            String thisAnnotation = this.getAnnotation(annotatedLines, i);
            String nextAnnotation = this.getAnnotation(annotatedLines, i + 1);
            if (thisAnnotation.equals("B-REF")) {
                addStartTag = true;
                if (!nextAnnotation.equals("I-REF")) {
                    addEndTag = true;
                }
            } else {
                if (thisAnnotation.equals("I-REF")) {
                    if (!nextAnnotation.equals("I-REF")) {
                        addEndTag = true;
                    }
                }
            }

            String thisLine = this.getLine(annotatedLines, i);
            if (addStartTag) {
                thisLine = "<ref>" + thisLine;
            }
            if (addEndTag) {
                thisLine = thisLine + "</ref>";
            }
            xmlAnnotatedLines.add(thisLine);
        }
        return xmlAnnotatedLines;
    }

    private String getAnnotation(List<ReferenceLineAnnotation> annotatedLines, int index) {
        if (annotatedLines.size() <= index) {
            return "";
        } else {
            return annotatedLines.get(index).getBestAnnotation();
        }
    }

    private String getLine(List<ReferenceLineAnnotation> annotatedLines, int index) {
        if (annotatedLines.size() <= index) {
            return "";
        } else {
            return annotatedLines.get(index).getLine();
        }
    }
}
```

I don't know what I am doing wrong? Isn't it the .csv file that we have to consider as the crfmodel file for training?

Thanks in advance and sorry if anything is confusing, I am a beginner.

**Comment by mkrnr** [comment]
Hi, sorry for the late reply.

If you want to build a CRF model file, this is the wrong class since it takes a model as an input to label training data. For building the CRF model, you should use [Main.java](https://github.com/mkrnr/refext/blob/master/src/main/java/de/exciteproject/refext/train/Main.java).
